language: php

sudo: required

dist: trusty

php:
  - '7.3'
  - '7.4'

os: linux

services: 
 - mysql

before_install:
 - mysql -e 'CREATE DATABASE testing;'

before_script:
 - composer install
 - cp .env.testing.example .env.testing
 - php artisan key:generate
# - php artisan jwt:secret

script:
 - vendor/bin/phpunit
 - php artisan code:analyse